### ISSUE TITLE
Can't run on iOS

### ISSUE THREAD

**Issue by flybayer** [expo/native-component-list#12]
Unless I'm missing something, the only way to run this project on iOS is to clone the code locally and run using `exp`. I tried this, but it's not working with this error:

```bash
/p/t/native-component-list> expo start
[11:18:08] Starting project at /private/tmp/native-component-list
[11:18:10] Error: Using unversioned Expo SDK. Do not publish until you set sdkVersion in app.json
[11:18:12] internal/modules/cjs/loader.js:583
[11:18:12]     throw err;
[11:18:12]     ^
[11:18:12]
[11:18:12] Error: Cannot find module '/private/tmp/native-component-list/rn-cli.config.js'
[11:18:12]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
[11:18:12]     at Function.Module._load (internal/modules/cjs/loader.js:507:25)
[11:18:12]     at Module.require (internal/modules/cjs/loader.js:637:17)
[11:18:12]     at require (internal/modules/cjs/helpers.js:20:18)
[11:18:12]     at Object.load (/private/tmp/native-component-list/node_modules/metro/src/Config.js:202:16)
[11:18:12]     at Object.load (/private/tmp/native-component-list/node_modules/react-native/local-cli/util/Config.js:103:24)
[11:18:12]     at getCliConfig (/private/tmp/native-component-list/node_modules/react-native/local-cli/core/index.js:139:14)
[11:18:12]     at Object.<anonymous> (/private/tmp/native-component-list/node_modules/react-native/local-cli/core/index.js:145:18)
[11:18:12]     at Module._compile (internal/modules/cjs/loader.js:689:30)
[11:18:12]     at loader (/private/tmp/native-component-list/node_modules/babel-register/lib/node.js:144:5)
[11:18:12] Metro Bundler process exited with code 1
[11:18:12] Error: Metro Bundler process exited with code 1
    at ChildProcess.<anonymous> (/xdl@51.2.4/src/Project.js:1472:14)
    at Generator.next (<anonymous>)
    at step (/Users/b/.config/yarn/global/node_modules/xdl/build/Project.js:2033:191)
    at /Users/b/.config/yarn/global/node_modules/xdl/build/Project.js:2033:437
    at new Promise (<anonymous>)
    at ChildProcess.<anonymous> (/Users/b/.config/yarn/global/node_modules/xdl/build/Project.js:2033:99)
    at ChildProcess.packagerProcess.once (/xdl@51.2.4/src/Project.js:1470:5)
    at Object.onceWrapper (events.js:273:13)
    at ChildProcess.emit (events.js:182:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
```

**Comment by davydovpv** [comment]
same error

**Comment by ide** [comment]
It looks like the problem is `Cannot find module '/private/tmp/native-component-list/rn-cli.config.js'` and that file might not be included in this repo. Native Component List has moved here: https://github.com/expo/expo/tree/master/apps/native-component-list where it runs, so you may want to try that instead.
